### ISSUE TITLE
Cannot stop timer, when started from dmenu

### ISSUE THREAD

**Issue by TudorAndrei** [wilsonchaney/pomodoro#4]
I use dmenu to start/stop the timer but one i start the timer from dmenu, i cannot stop it.

I tried running the cancel script from the terminal and dmenu. The only way to stop it, is to manually kill it.

**Comment by TudorAndrei** [comment]
I think I fixed it, I changed the script to do a SIGKILL.

**Comment by wilsonchaney** [comment]
Hi Tudor - I pushed https://github.com/wilsonchaney/pomodoro/commit/20cf068eaeac175cf8624ee19979f2bc79624913 which should fix this (just using SIGTERM instead of SIGKILL) - let me know if you have any other issues!
